### ISSUE TITLE
Make it look better.... please

### ISSUE THREAD

**Issue by bdougie** [open-sauced/swag#6]
![Screen Shot 2020-08-28 at 3 21 35 PM](https://user-images.githubusercontent.com/5713670/91619550-384e7280-e942-11ea-8616-43a08898ca53.png)

- [x] shopping-cart sticky and flexed on the right.
- [x] remove links in the footer
- [ ] dark header
- [x] address mobile views

**Comment by thinkverse** [comment]
Pushed PR (#8) to fix the tailwind gradient issue, also added a new page where you can mess around with it, hope you like it. 👍

**Comment by bdougie** [comment]
I think we are there.
